### PR TITLE
Use Alex-generated lexer instead of ad hoc one

### PR DESCRIPTION
**Pull request by sergv**
I've updated lexer to use proper Alex-based token detection instead of some ad hoc rules. This is still not quite Haskell since it does not distinguish numbers and does not track strings, character literals and quasiquoter contents, but those are not really relevant for tag detection that is already being performed.

This change speeds up tag generation a bit, although it doesn't make it instantaneous (yet). Among other things, proper lexer enables fast-tags to distinguish tokens like Template Haskell's `$(` from `$ (`, which improves precision somewhat. Thus the elaforge/fast-tags#16 should be closed.

### CODE REVIEW

**Comment by osa1** [comment]
Awesome work, @sergv ! I just tried your implementation on GHC repo. Previously tag generation was taking 5.92s, with your implementation it takes 2.98s! I also compared generated tags, and it seems like your implementation is better in generated tags too.

One thing that's worse is sometimes wrong tags are generated. Here's the diff file of tags generated by your implementation and current implementation:

```diff
--- tags_original	2015-12-31 15:41:56.188603983 -0500
+++ tags	2015-12-31 15:44:14.747601975 -0500
@@ -1,4 +1,14 @@
 !_TAG_FILE_SORTED	1	~
+#	compiler/stage1/build/CmmLex.hs	344;"	o
+#	compiler/stage1/build/Parser.hs	10094;"	o
+#	compiler/stage2/build/Parser.hs	10094;"	o
+#	compiler/utils/Util.hs	485;"	o
+#	compiler/stage1/build/CmmParse.hs	2894;"	o
+#	compiler/stage1/build/Lexer.hs	2495;"	o
+#	compiler/main/SysTools.hs	96;"	o
+#	compiler/stage2/build/CmmLex.hs	344;"	o
+#	compiler/stage2/build/Lexer.hs	2495;"	o
+#	compiler/stage2/build/CmmParse.hs	2894;"	o
 $$	compiler/utils/Pretty.hs	642;"	o
 $$	compiler/utils/Outputable.hs	581;"	o
 $+$	compiler/utils/Pretty.hs	647;"	o
@@ -21,14 +31,6 @@
 <||>	compiler/utils/Util.hs	703;"	o
 =:	compiler/coreSyn/CoreTidy.hs	271;"	o
 ===	compiler/typecheck/TcTypeNats.hs	304;"	o
-=>	compiler/hsSyn/HsSyn.hs	110;"	o
-=>	compiler/hsSyn/HsExpr.hs	521;"	o
-=>	compiler/hsSyn/HsDecls.hs	151;"	o
-=>	compiler/hsSyn/HsLit.hs	85;"	o
-=>	compiler/hsSyn/HsTypes.hs	252;"	o
-=>	compiler/hsSyn/HsPat.hs	222;"	o
-=>	compiler/hsSyn/HsBinds.hs	86;"	o
-=>	compiler/basicTypes/FieldLabel.hs	105;"	o
 >.>	compiler/coreSyn/TrieMap.hs	85;"	o
 A	compiler/basicTypes/OccName.hs	388;"	C
 ABE	compiler/hsSyn/HsBinds.hs	239;"	C
@@ -4503,14 +4505,8 @@
 PostInlineUnconditionally	compiler/simplCore/CoreMonad.hs	394;"	C
 PostLoadMode	ghc/Main.hs	458;"	t
 PostRn	compiler/hsSyn/PlaceHolder.hs	45;"	t
-PostRn	compiler/hsSyn/PlaceHolder.hs	46;"	t
-PostRn	compiler/hsSyn/PlaceHolder.hs	47;"	t
-PostRn	compiler/hsSyn/PlaceHolder.hs	48;"	t
 PostStartupMode	ghc/Main.hs	406;"	t
 PostTc	compiler/hsSyn/PlaceHolder.hs	39;"	t
-PostTc	compiler/hsSyn/PlaceHolder.hs	40;"	t
-PostTc	compiler/hsSyn/PlaceHolder.hs	41;"	t
-PostTc	compiler/hsSyn/PlaceHolder.hs	42;"	t
 PostTcExpr	compiler/hsSyn/HsExpr.hs	63;"	t
 PostTcTable	compiler/hsSyn/HsExpr.hs	66;"	t
 PprCode	compiler/utils/Outputable.hs	143;"	C
@@ -7458,7 +7454,7 @@
 cTyConName	compiler/prelude/PrelNames.hs	873;"	f
 cUpper	compiler/parser/Ctype.hs	26;"	f
 c_Expr	compiler/typecheck/TcGenDeriv.hs	2363;"	f
-c_GetModuleFileName	compiler/main/SysTools.hs	1501;"	p
+c_GetModuleFileName	compiler/main/SysTools.hs	1500;"	f
 c_Pat	compiler/typecheck/TcGenDeriv.hs	2381;"	f
 c_RDR	compiler/typecheck/TcGenDeriv.hs	2344;"	f
 cab_cvs	compiler/types/CoAxiom.hs	227;"	f
@@ -10113,7 +10109,7 @@
 en_locale_env	compiler/main/SysTools.hs	547;"	f
 enableGlasgowExts	compiler/main/DynFlags.hs	3477;"	f
 enableTimeStats	compiler/main/DynFlags.hs	594;"	f
-enableTimingStats	compiler/main/DynFlags.hs	4433;"	p
+enableTimingStats	compiler/main/DynFlags.hs	4433;"	f
 enableUnusedBinds	compiler/main/DynFlags.hs	3464;"	f
 enclosingTickSpan	ghc/GHCi/UI.hs	2922;"	f
 encodeDoubleIntegerIdKey	compiler/prelude/PrelNames.hs	1948;"	f
@@ -11558,7 +11554,7 @@
 genSwitch	compiler/nativeGen/X86/CodeGen.hs	2595;"	f
 genSwitch	compiler/llvmGen/LlvmCodeGen/CodeGen.hs	999;"	f
 genSwitch	compiler/nativeGen/SPARC/CodeGen.hs	313;"	f
-genSym	compiler/basicTypes/UniqSupply.hs	92;"	p
+genSym	compiler/basicTypes/UniqSupply.hs	92;"	f
 genTrivialCode	compiler/nativeGen/X86/CodeGen.hs	2831;"	f
 genUnitDataConKey	compiler/prelude/PrelNames.hs	1788;"	f
 gen_Bounded_binds	compiler/typecheck/TcGenDeriv.hs	665;"	f
@@ -11995,7 +11991,7 @@
 getOptions'	compiler/main/HeaderInfo.hs	228;"	f
 getOptionsFromFile	compiler/main/HeaderInfo.hs	140;"	f
 getOpts	compiler/main/DynFlags.hs	1843;"	f
-getOrSetLibHSghcFastStringTable	compiler/utils/FastString.hs	255;"	p
+getOrSetLibHSghcFastStringTable	compiler/utils/FastString.hs	254;"	f
 getOrigNameCache	compiler/simplCore/CoreMonad.hs	700;"	f
 getOrphanHashes	compiler/iface/MkIface.hs	594;"	f
 getOutEdges	compiler/nativeGen/AsmCodeGen.hs	774;"	f
@@ -12051,7 +12047,7 @@
 getPrintUnqualified	compiler/simplCore/CoreMonad.hs	681;"	f
 getPrintUnqualified	compiler/typecheck/TcRnMonad.hs	559;"	f
 getProcessID	compiler/main/SysTools.hs	1509;"	f
-getProcessID	compiler/main/SysTools.hs	1507;"	p
+getProcessID	compiler/main/SysTools.hs	1507;"	f
 getProgramDynFlags	compiler/main/GHC.hs	626;"	f
 getQCONID	compiler/stage1/build/Parser.hs	9798;"	f
 getQCONID	compiler/stage2/build/Parser.hs	9798;"	f
@@ -18076,7 +18072,7 @@
 initFreeRegs	compiler/nativeGen/RegAlloc/Linear/SPARC/FreeRegs.hs	46;"	f
 initFreeRegs	compiler/nativeGen/RegAlloc/Linear/PPC/FreeRegs.hs	41;"	f
 initFreeRegs	compiler/nativeGen/RegAlloc/Linear/X86_64/FreeRegs.hs	28;"	f
-initGCStatistics	ghc/Main.hs	943;"	p
+initGCStatistics	ghc/Main.hs	942;"	f
 initGhcMonad	compiler/main/GHC.hs	496;"	f
 initGraph	compiler/utils/GraphBase.hs	50;"	f
 initHpUsage	compiler/codeGen/StgCmmMonad.hs	418;"	f
@@ -18114,7 +18110,7 @@
 initTidyOccEnv	compiler/basicTypes/OccName.hs	842;"	f
 initTyVarUnique	compiler/basicTypes/Unique.hs	364;"	f
 initUM	compiler/types/Unify.hs	936;"	f
-initUniqSupply	compiler/basicTypes/UniqSupply.hs	93;"	p
+initUniqSupply	compiler/basicTypes/UniqSupply.hs	93;"	f
 initUpdFrameOff	compiler/codeGen/StgCmmMonad.hs	320;"	f
 initUpdFrameProf	compiler/codeGen/StgCmmProf.hs	90;"	f
 initUs	compiler/basicTypes/UniqSupply.hs	146;"	f
@@ -20434,7 +20430,7 @@
 memConflicts	compiler/cmm/CmmSink.hs	673;"	f
 memConstant	compiler/nativeGen/X86/CodeGen.hs	1224;"	f
 memberInstEnv	compiler/types/InstEnv.hs	395;"	f
-memcmp	compiler/utils/FastString.hs	214;"	p
+memcmp	compiler/utils/FastString.hs	213;"	f
 memptyClassOpKey	compiler/prelude/PrelNames.hs	2166;"	f
 memptyName	compiler/prelude/PrelNames.hs	989;"	f
 mempty_Expr	compiler/typecheck/TcGenDeriv.hs	2364;"	f
@@ -22820,9 +22816,13 @@
 out_of_date_hash	compiler/iface/MkIface.hs	1251;"	f
 outdegreeG	compiler/utils/Digraph.hs	279;"	f
 outerLevel	compiler/typecheck/TcRnTypes.hs	806;"	f
+outputAsm	compiler/main/CodeOutput.hs	142;"	f
 outputC	compiler/main/CodeOutput.hs	100;"	f
 outputFile	compiler/main/DynFlags.hs	651;"	f
+outputForeignStubs	compiler/main/CodeOutput.hs	183;"	f
+outputForeignStubs_help	compiler/main/CodeOutput.hs	249;"	f
 outputHi	compiler/main/DynFlags.hs	653;"	f
+outputLlvm	compiler/main/CodeOutput.hs	167;"	f
 output_spec	compiler/main/PipelineMonad.hs	57;"	f
 overLitType	compiler/hsSyn/HsLit.hs	95;"	f
 overlapInstLoc	compiler/main/DynFlags.hs	742;"	f
@@ -24199,7 +24199,7 @@
 ptext	compiler/utils/Outputable.hs	486;"	f
 ptr	compiler/ghci/ByteCodeAsm.hs	186;"	f
 ptrCount	compiler/ghci/ByteCodeAsm.hs	242;"	f
-ptrStrLength	compiler/utils/FastString.hs	596;"	p
+ptrStrLength	compiler/utils/FastString.hs	595;"	f
 ptrTyConKey	compiler/prelude/PrelNames.hs	1578;"	f
 ptrTyConName	compiler/prelude/PrelNames.hs	1300;"	f
 ptrs	compiler/ghci/RtClosureInspect.hs	159;"	f
@@ -25240,14 +25240,14 @@
 rtldInfo	compiler/main/DynFlags.hs	803;"	f
 rtsBuildTag	compiler/main/DynFlags.hs	623;"	f
 rtsClosureType	compiler/cmm/SMRep.hs	426;"	f
-rtsIsDynamicIO	compiler/main/DynFlags.hs	3530;"	p
+rtsIsDynamicIO	compiler/main/DynFlags.hs	3530;"	f
 rtsIsProfiled	compiler/main/DynFlags.hs	3522;"	f
-rtsIsProfiledIO	compiler/main/DynFlags.hs	3519;"	p
+rtsIsProfiledIO	compiler/main/DynFlags.hs	3519;"	f
 rtsOpts	compiler/main/DynFlags.hs	671;"	f
 rtsOptsEnabled	compiler/main/DynFlags.hs	672;"	f
 rtsOptsSuggestions	compiler/main/DynFlags.hs	673;"	f
 rtsUnitId	compiler/basicTypes/Module.hs	390;"	f
-rts_revertCAFs	ghc/GHCi/UI/Monad.hs	384;"	p
+rts_revertCAFs	ghc/GHCi/UI/Monad.hs	384;"	f
 rttiEnvironment	compiler/main/InteractiveEval.hs	581;"	f
 ru_act	compiler/coreSyn/CoreSyn.hs	841;"	f
 ru_args	compiler/coreSyn/CoreSyn.hs	851;"	f
@@ -25801,7 +25801,7 @@
 setGeneralFlag'	compiler/main/DynFlags.hs	3657;"	f
 setGlobalTypeEnv	compiler/typecheck/TcEnv.hs	256;"	f
 setHcSuf	compiler/main/DynFlags.hs	1859;"	f
-setHeapSize	compiler/main/DynFlags.hs	4432;"	p
+setHeapSize	compiler/main/DynFlags.hs	4432;"	f
 setHiDir	compiler/main/DynFlags.hs	1856;"	f
 setHiSuf	compiler/main/DynFlags.hs	1859;"	f
 setHpUsage	compiler/codeGen/StgCmmMonad.hs	439;"	f
```

See how tags are generated from CPP macro lines. It'd be great if you could fix this.

**Comment by elaforge** [comment]
I tried this on my source and there are a few minor differences:

1 - Bogus tags from hsc #xyz lines.  Known issue from above.

2 - Many tags previously incorrectly marked as 'p' Pattern are now correctly 'f' Function.

3 - Line numbers are a little off for wrapped lines, e.g. given:

> foreign import ccall "clear_logs"
>     c_clear_logs :: Ptr Window -> IO ()

The old one puts c_clear_logs on the second line, the new one puts it on the first line.  Not really a big deal, but would be nice to fix if it's not super complicated.

And of course the new one is faster:

> % time fast-tags $hs
> fast-tags $hs  1.57s user 0.08s system 94% cpu 1.750 total
> % time fast-tags-new $hs
> fast-tags-new $hs  1.09s user 0.07s system 92% cpu 1.261 total

Other than that, all the tags are the same for my project.

**Comment by sergv** [comment]
I fixed preprocessor issues and line numbers for foreign tags. In addition, stripping characters in chunks should speed things up a little bit.

Another improvement is stripping of multiline preprocessor definitions like
```haskell
#define FOO(x) = foo \
   bar x
```

**Comment by osa1** [comment]
Great, I think generated tags are in good shape now. (I didn't realize any performance improvements, but it was improved significantly already!)

**Comment by elaforge** [comment]
This looks good to me, so I'll merge.

Thanks for the speed boost!  I'm going to commit some minor cleanups I've had sitting in my client, do a bit more testing, and then since this is a big improvement, bump the version and push to hackage.

**Pull request merged**
