### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by sergv**
A fix for #36

### CODE REVIEW

**Comment by elaforge** [comment]
It looks like the build is now working, but the tests line is failing, maybe it needs --allow-newer=Cabal too?

That said, I don't really understand why that fixes the problem.  Also, the travis config was automatically generated by hvr's script.  I feel like we should either figure out why it's broken with alex (and why only on 8.4.1) and then fix the problem in the original script, or abandon the script altogether and write a nicer config from scratch.  The script generated version has a lot of junk that makes it hard to read and modify, but comes with the ability to test against ghc HEAD and at least the promise of being maintained by someone else while constant ghc churn inevitably breaks something every 6 months or so.

**Comment by sergv** [comment]
I think the issue lies with this bit form `cabal new-{build,test,etc}`:

```
rejecting: alex:setup.Cabal-2.2.0.0/installed-2.2...,
alex:setup.Cabal-2.2.0.0 (conflict: fast-tags:alex:exe.alex =>
alex:setup.Cabal>=1.8 && <1.25)
```

The `ghc` compilet comes pre-bundled with `Cabal-2.2`, but the most recent `alex` (`3.2.3` at the time of writing) imposes constrains on version of `Cabal` because `alex` has custom `Setup.hs`. These constrains seem to be pretty tight - strictly less than `1.25`, so `Cabal-2.2` does not cut it.

The situation is fine with `cabal-install-2.0` because it seems to just re-use `alex` already available in `PATH`.

I have little experience with hvr's script, but I was manually tweaking Travis scritps lately. Please take a look at `.travis.yml` for `flycheck-haskell` (an emacs package for on-the-fly syntax checking): https://github.com/flycheck/flycheck-haskell/blob/master/.travis.yml. It tests over a wide range of GHC versions (perhaps too wide), but is less overloaded with various commands. I can try to make something similar for `fast-tags`.

**Comment by sergv** [comment]
It's actually pretty interesting how `cabal-install` managest to infer constraint `Cabal >= 1.8 < 1.25` for `alex` given that `alex.cabal` does not impose upper bound on the `Cabal` package.

**Comment by sergv** [comment]
@elaforge I found a way to make CI green again. But I used "legacy" `cabal {configure,bulid,install,test}` commands to do that. Arguably they're not legacy yet since `new-build` is still not the default mode of operation (and a bit rough at the edges as we have seen cf alex Setup.hs constaints on Cabal package). Are you comfortable with using these commands?

**Comment by elaforge** [comment]
Ok, this looks good to me.  I was mostly just wanting to learn about travis and new-build, but as you say it still seems to be a bit rough.  As far as I can tell the tool stuff with new cabal isn't really documented, maybe I can get that fixed.

The one thing I can think of where the new-build stuff might be good, is that it seems like with the usual way as various libraries get updated, the cache might eventually get into one of those triangle import conflicts where you have to either force reinstall or just wipe out the cache and start again.  It seems like the new-build stuff should be able to handle that better.

In any case, I'm not worried about that stuff for such a simple project.

And of course thanks for fixing this!

**Comment by sergv** [comment]
Yes, `cabal new-build` should play nicely with caches. But there's also an option with `stack`, which should also play nicely with caches /and/ is future proof w.r.t. future versions of packages. With cabal, if versions are not pinned down then future versions of dependencies may change API and make this project non-buildable, whereas stack pins them to specific versions from the snapshot.

**Comment by elaforge** [comment]
That's true, though you could also say it's a good thing to see the things that break as soon as they do. 
 I guess with stack you get your breakage all one go when you want to switch to a new stack "world", while with plain hackage you get it in little bits over time.  I'm actually not sure which is better, I might actually prefer the one big upgrade after all.  I guess for applications you can stick to a certain stack LTS, but for libraries you'd want to find out about version bound breakage sooner.

**Pull request merged**
