### PR TITLE
Some enhancements

### PR DESCRIPTION
**Pull request by sergv**
Hi, this is pull request of some features added to fast-tagsin period after version 0.0.5 when it wasn't particularly actively developed in the main repository.

New features include:
* recognize more syntactic constructs (consider tests as specification of what's handled)
* add more tests
* use tasty to organize tests
* ability to produce emacs tags
* handling of literate files
* new mode to recursively traverse directory tree and search for haskell files
* optionally ignore encoding errors during reading and skip offending files
* ability to read \n-separated or \0-separated list of files from stdin
* and blazing-fast speed of tag generation is presevred

I realize that this pull request is anything but atomic but it contains some useful features that I believe should be in the official repository.

### CODE REVIEW

**Comment by elaforge** [comment]
Ok, I checked out the changes and have some comments below.  I'm going to go ahead and merge this now.

Firstly, thanks for all the patches!  As you noticed, I haven't been updating,
but it's because it works for me, not because I've abandoned it.  But bug fixes
and speed improvements are always very appreciated!

And sorry again about the delay, for a while github was completely blocked in
India.

I notice the 'fast' flag does make compilation quite slow, so you definitely
want it off for development, but for 'cabal install' probably it should default
to on, right?  I mean, if the speed improvement is significant.  If not
significant though, we probably don't need the flag at all.  However, in my
totally unscientific tests with 'time', it doesn't make any difference.
Under what circumstances were you able to get the improvement mentioned
in the cabal file?

Is there no way to factor out the flags copy-paste in the cabal file?  Sorry, I
don't know much about cabal...

It looks like your formatting style is a bit different.  I don't mind though
because there are so many good changes.  But I'll probably add another patch to
make it consistent again.  And fix up the non-exhaustive pattern match
warnings.

I'm nervous about 'error' calls, e.g. tokenName.  If it's awkward to avoid them
I think they should at least come with a comment explaining why it's impossible
they occur, and maybe why it's awkward to do it right.  It's not because I mind
crashing, in a small program like this it's not a problem to crash with a nice
msg, but it's easier to understand and modify the code without runtime errors.


Differences in tags output:

It looks like it's now picking up @ pattern match aliases as operators.  I'll
add a test to demonstrake and try to fix it.  Unless you would like to :)

Given:

    newtype AttributeMap =
        AttributeMap [(Score.Attributes, [Keyswitch], Maybe Keymap)]
        deriving (Eq, Show, Pretty.Pretty, DeepSeq.NFData)

It used to detect the AttributeMap constructor on the next line, but no longer does.

Sort order is slightly different, and some type tags have changed.  I'm pretty sure this is intentional, right?

It's now detecting a bunch of functions that lack type declarations.  Also foreign imports are now detected.  I didn't mind omitting those before because my convention is that functions like that are always module internal.  But I think this is probably a good thing in general, given that maybe other people like to export these.  And of course I guess it's nice for tag jumps inside the module to work :)  I always use * or # for those, so I never noticed.

In unscientific but consistent checks with 'time', it's slowed down a bit:

    % rm tags; time fast-tags $fs
    fast-tags $fs  0.72s user 0.03s system 99% cpu 0.754 total
    % rm tags; time fast-tags-new $fs
    fast-tags-new $fs  1.10s user 0.04s system 99% cpu 1.136 total

But this is for a complete run, over 534 files generated 12158 tags (the old
fast-tags is generating only 10474).  Since the difference is small, and most
of the time it's an incremental run, I think the slow down is not a big deal.

**Comment by elaforge** [comment]
Also, once we've discussed these things I'll bump the version and upload to hackage.  Though I have a feeling you and I are the only real users... but then again until this pull request showed up I thought I was the only user.

**Comment by sergv** [comment]
Hi and thanks for reply. We're certainly not the only users out there since the fast tags are really fast and our team uses it at work. It's nice that the project is not abandoned, even though there're not many updates lately.

The ``fast`` option works best if you also build all dependencies with similar ghc options. So it actually takes even more time than you probably observed and there's no way to specify in cabal file that dependencies should be built this way. Also I thrown together a bit more "scientific" benchmark with criterion and here're the numbers for ~39Mb input:

```
total length of input: 39076548 characters
benchmarking FastTags
time                 8.781 s    (8.695 s .. 8.822 s)
                     1.000 R²   (NaN R² .. 1.000 R²)
mean                 8.707 s    (8.684 s .. 8.728 s)
std dev              35.66 ms   (0.0 s .. 36.64 ms)
variance introduced by outliers: 19% (moderately inflated)

benchmarking FastTagsOpt
time                 7.219 s    (7.061 s .. 7.327 s)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 7.140 s    (7.114 s .. 7.149 s)
std dev              25.93 ms   (0.0 s .. 29.93 ms)
variance introduced by outliers: 19% (moderately inflated)
```

The `FastTags` is plain FastTags module and `FastTagsOpt` is copy of FastTags module with `{-# OPTIONS_GHC -funfolding-creation-threshold=10000 -funfolding-use-threshold=2500 #-}` line added.

The speedup here is around 20%. I was reluctant to enable this flag by default because it increases compilation time and memory consumption. But maybe we should enable it by default so users will get the speedup. On the other hand if users are going to use it on small code bases then there's no much value for them to be gained here, but they'll have to sit through longer compilation.

NB My use case is that I usually download sources for all the packages used in a project and index them with fast tags so I can immediately see what given unfamiliar function is doing. So naturally I have to feed a lot of files to fast tags and I'd like not to wait long. And that's where ~39Mb input in benchmark comes from.


The cabal file unfortunately has to have some duplication, but I tried to decrease it to a minimum - most of the dependencies are grouped in the library section, and then library gets re-used for executable and tests. Since both executable and tests use Data.Text the text package has to be added to their build dependends and hence the duplication.


I changed the formatting style since at some point I stopped hoping to merge my changes into the main repository. I realize that it's unethical to diverge from the style already used in the project, sorry for that. Perhaps you could make use of https://github.com/chrisdone/hindent to automatically fix the style, but I haven't tried it for myself.

The non-exhaustive pattern-match warnings are of the "cannot happen" type since it's newline tags it warns about, but newlines should be stripped away at that point in source. Perhaps the problem can be solved by using GADT for `TokenVal` datatype indexed with whether it contains newlines or not, e.g.

```Haskell
data NoNewlines
data HasNewlines
data TokenVal ix where
  Token   :: Text -> Text -> TokenVal ix
  Newline :: Int -> TokenVal HasNewlines

type UnstrippedTokens = [TokenVal HasNewlines]
type StrippedTokens = [TokenVal NoNewlines]

unstrippedTokensOf :: UnstrippedTokens -> StrippedTokens
... -- implementation of unstrippedTokensOf omitted

type Token = Pos (TokenVal NoNewlines)

-- This way when implementing tokToTag function like this
-- there will be no pattern-match error due to GADT index ensuring that
-- no newlines are allowed.
tokToTag :: Token -> Type -> Tag
tokToTag (Pos pos (Token prefix name)) t = mkTag pos prefix name t

```

Again, regarding error call in tokenName - this is the same as non-exhaustive pattern match - no newlines should make it into tokenName. GADT approach outlined above can solve it too:

```Haskell
tokenName :: TokenVal NoNewlines -> Text
tokenName (Token _ name) = name
-- this line will just not type check if present in the source, so it'll have be omitted
tokenName (Newline _) = undefined

```

Other sources of errors, as I observe, are:
+ combineBalanced function - it's purpose is to perform the "merge" phase of the merge sorting algorithm with the given merge-like function and errors guard agains some invariants.
+ collectRest local function of collectRest dataConstructorTags - it looks like a bug and error should be turned into invokation of unexpected function


Picking of @ patterns match aliases is a bug and I can fix that, thanks for catching this. When detecting functions without type signatures I have to employ some heuristics no not confuse !-patters, ~-patterns with the function or operator being defined.


Regarding detection of `AttributeMap` from your example it was my idea that when type name and constructor name are the same and they're close then there's no need to report constructor name because the same information is contained in the type name. Perhaps it's specialized to the way I use fast-tags, but now I think it was a bad idea ind I'll restore the previous behavior in the followup pull request.


Sorting did change a bit, mainly because of detection of functions without type signatures. Turns out such functions tend to have many clauses, but only one of them should make it into a tag definition. So I added repeatable tags and changed process to do some sorting on its own. Another change is that sortDups used to call List.groupBy function, which is quadractic so I tried to avoid that.


Regarding detection of functions without type signatures, maybe we could add command-line flag to disable some detections. And while your convention makes perfect sense, I tend to run fast-tags on all kinds of sources, and not all of them agree on the use of type signatures.

I'm a bit confused about your time benchmark, is `fast-tags` executable the old one before my patches and `fast-tags-new` is the newer one with `fast` flag enabled?

Or is `fast-tags-new` just the new one without the `fast` flag? In such a case perhaps some slowdown may be justified by increased complexity of tag-detection functions.

Once we're finished, would you like to make some kind of announcement? Perhaps fast tags that work regardless of whether file can be parsed or uses preprocessor could be of use to others?

**Comment by elaforge** [comment]
About -f fast: Ok, sounds like it can indeed help.  Let's leave it as-is, defaulting to false then.  I only tag per-project so for people like me the "slow" version is already fast enough.

cabal file duplication: no problem, I guess it's unavoidable.

formatting: unfortunately hindent only support's Chris Done's own style, and a little bit of Johan's.  I can make things consistent by hand, it's only one source file, though a big one.  If I were starting again, or hindent had complete support for Johan's I'd probably adopt his style for consistency, it differs from mine only in minor ways.

Sorting change is not a problem.  Vim goes to the first tag first, so they should generally go in "most likely" order... but who knows what that is really, so really anything consistent is good.  If the first tag is consistently not the one you want, we can collect such examples to come up with a better heuristic.

Actually, I would prefer to reduce the ambiguity by using the qualified notation.  Unfortunately while vim can do this, it has the side-effect of putting '.' in the identifier list, which messes up motions like 'w'.  Maybe if emacs doesn't have that problem or if I come up with a way around the vim problem, we can add a flag to include 'Module.symbol' in addition to 'symbol'.

About functions without type signatures, I think you are correct to detect them anyway.  Many people are inconsistent about signatures.  And lack of signature is not a good way to say "omit tags".  So let's keep your change, no flag necessary.

In my timing, fast-tags was the old version, before your pull request.  fast-tags-new is after your pull request, without the fast flag.  I found no difference in time after adding the fast flag.  So your changes do seem to make it noticeably slower, though still fast enough for me.  However, your changes are also detecting more tags, that can explain the difference.

I did announce fast-tags on haskell-cafe a long time ago.  Perhaps it could do with another announcement since it's been a long time, so I'll do that when I bump the version.

**Pull request merged**
